import { ATRIBUTOS, PERICIAS_GRUPOS } from "../data/gameData";

export const uid = () => Math.random().toString(36).slice(2, 10);

export const novaFicha = (nome = "Novo Personagem") => ({
  id: uid(),
  nome,
  raca: "Humano",
  racaSecundaria: "",
  racasExtras: [],
  classes: [],
  titulos: ["Aventureiro"],
  tituloSelecionado: "Aventureiro",
  essencia: null,
  exposicao: 0,
  exposicaoDetalhada: {
    tipoVisual: "pizza",
    perkExposicao: "Ecdise",
    perkVariacao: "Padrão",
    tipoCorpo: "Corpo Comum",
    corpoEssenciaVinculada: "",
    exposicoes: {},
  },
  aparencia: "",
  historico: "",
  notas: "",
  informacoes: {
    peso: "",
    altura: "",
    genero: "",
    rank: "Comum",
    avatarModo: "fallback",
    avatarIcone: "?",
    avatarCor: "#1b2330",
    avatarUrl: "",
    avatarData: "",
  },
  status: {
    VIT:  { val: 20, max: 20 },
    EST:  { val: 15, max: 15 },
    MAN:  { val: 10, max: 10 },
    SAN:  { val: 20, max: 20 },
    CONS: { val: 15, max: 15 },
  },
  atributos: Object.fromEntries(ATRIBUTOS.map((a) => [a.sigla, { val: 5, ae: false, ne: false }])),
  pericias: Object.fromEntries(PERICIAS_GRUPOS.flatMap((g) => g.list.map((p) => [p, 0]))),
  periciaPrestigios: {},
  recursos: {
    ACO: { total: 2, usado: 0 },
    MOV: { total: 1, usado: 0 },
    REA: { total: 1, usado: 0 },
    ESF: { total: 1, usado: 0 },
  },
  inventario: [],
  corpo: {
    pontosTotal: 1000,
    partes: [],
    links: [],
  },
  combate: {
    rodadaAtual: 0,
    abaAtiva: "recursos",
    lembretes: [],
    efeitos: [],
    recursos: [
      { id: uid(), nome: "MOV", cor: "#28a745", max: 0, atual: 0 },
      { id: uid(), nome: "ACO", cor: "#007bff", max: 0, atual: 0 },
      { id: uid(), nome: "REA", cor: "#dc3545", max: 0, atual: 0 },
      { id: uid(), nome: "ESF", cor: "#8b0000", max: 0, atual: 0 },
    ],
  },
  inventarioCfg: {
    slotsBase: 10,
    capacidadePorForca: 5,
    ajustes: [],
    vastos: { cobre: 0, prata: 0, ouro: 0, platina: 0 },
  },
  modificadores: {
    efeitos: [],
    status: [],
    atributos: [],
    pericias: [],
  },
  criado: Date.now(),
  atualizado: Date.now(),
});

export const novoItem = () => ({
  id: uid(),
  nome: "Novo Item",
  iconeModo: "emoji",
  icone: "?",
  iconeUrl: "",
  iconeData: "",
  tipo: "Arma",
  rank: "Comum",
  subtipo: "",
  subtipoOutro: "",
  comentario: "",
  regiaoEfeito: "",
  regiaoEfeitoOutro: "",
  essenciaAtribuida: "",
  peso: 0,
  slots: 1,
  vastos: { cobre: 0, prata: 0, ouro: 0, platina: 0 },
  dano: "",
  critico: "",
  alcance: "",
  tamanho: "",
  defesa: "",
  regiao: "",
  efeitoCorpo: "",
  tags: [],
  quantidade: 1,
  consumo: 1,
  empilhavel: true,
  quantidadeMax: 1,
  gastoPorUso: 1,
  consumoTipo: "quantidade",
  bonus: [{ id: uid(), nome: "", descricao: "", valor: "", ativo: true }],
  efeitos: [],
  descricao: "",
  criado: Date.now(),
});

export const novaSkillTag = () => ({
  id: uid(),
  nome: "Nova Tag",
  cor: "#7aa9d8",
  descricao: "",
  criado: Date.now(),
});

export const novaSkill = () => ({
  id: uid(),
  nome: "Nova Skill",
  iconeModo: "fallback",
  icone: "?",
  iconeUrl: "",
  iconeData: "",
  iconeAjuste: null,
  cor: "#4a6088",
  tagIds: [],
  dono: "",
  alcance: "",
  custos: [],
  custoCatalogo: [
    { id: uid(), nome: "ACO", cor: "#22ee5f" },
    { id: uid(), nome: "MOV", cor: "#227de6" },
    { id: uid(), nome: "REA", cor: "#d31515" },
    { id: uid(), nome: "ESF", cor: "#290404" },
    { id: uid(), nome: "VIT", cor: "#f1250e" },
    { id: uid(), nome: "EST", cor: "#f9f100" },
    { id: uid(), nome: "MAN", cor: "#0077ff" },
    { id: uid(), nome: "SAN", cor: "#ff4dc4" },
    { id: uid(), nome: "CONS", cor: "#1abc9c" },
  ],
  rolagemTipo: "Padrão",
  rolagemPericia: "",
  rolagemAcao: "Ataque",
  rolagemInstrucao: "",
  geracao: 1,
  rank: "Comum",
  essenciaAtribuida: "Nenhuma",
  descricao: "",
  descricaoCode: "",
  criado: Date.now(),
  atualizado: Date.now(),
});
